### ISSUE TITLE
Not working with Fluent

### ISSUE THREAD

**Issue by brasileric** [axllent/silverstripe-meta-editor#1]
Hi,
It seems the editor is not working with Fluent? After changes the message appears that it's saved, but in fact nothing is saved.

**Comment by axllent** [comment]
This would make sense, as this module only modifies `SiteTree` and `SiteTree_Live` tables directly (`DB`), and Fluent apparently uses a different subset of linked tables, namely `SiteTree_Localised` and `SiteTree_Localised_Live` ([ref](https://github.com/tractorcow-farm/silverstripe-fluent/blob/4.4/docs/en/how-fluent-works.md)).

For this to work silverstripe-meta-editor would need to detect first if Fluent is installed, and then modify different tables (I suspect) - so basically a Fluent-specific hack that may or may not be easy to implement. I'm always cautious when doing this because what about the next module, or the next, or the next. However in saying that, I think Fluent is the "go-to" when it comes to multi-lingual SilverStripe 4 modules, so it may be worth me investigating to see if it is even possible. I will leave this open, however cannot guarantee I will get this looked into any time soon.

Pull requests (tested) welcome ;-)

**Comment by brasileric** [comment]
Hi Ralph. Thanks for response. I will look for an solution by myself as well. If fixed this I will post it here.

**Comment by axllent** [comment]
Hi Eric. Just so you're aware, I started on a solution for this last night and I should have something for you in the next day or so for testing.

**Comment by axllent** [comment]
Eric, please would you test the fluent branch for me to confirm that it works properly before I merge this in?

`composer require axllent/silverstripe-meta-editor:dev-fluent`

**Comment by brasileric** [comment]
Hi Ralph,

I just tested your update and it works perfect now with Fluent in my Silverstripe 4.5.0 project!

Thanks a lot for your quick work. How can I buy you a beer or coffee?

**Comment by axllent** [comment]
Thanks for testing that Eric, appreciated. I have just published a new [1.1.0 release](https://github.com/axllent/silverstripe-meta-editor/releases/tag/1.1.0) which contains the fluent functionality you tested earlier.

A beer would be definitely go down well, thank you ;-) https://www.axllent.org/donate/
